databases:
  - name: scrimverse_db
    databaseName: scrimverse
    user: scrimverse_user

services:
  - type: web
    name: scrimverse-backend
    env: python
    pythonVersion: "3.11"
    buildCommand: "./build.sh"
    startCommand: "gunicorn scrimverse.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scrimverse_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
